### ISSUE TITLE
Problems compiling and no power

### ISSUE THREAD

**Issue by dknubben** [hardkernel/smartpower3#10]
Hello,

I want to test the new version with the changes for CRLF and removed '\0' but I have two problems with the firmware:

1. If I use the latest sources without modifications (board = esp32dev) I get this error:

libraries/ESP32Encoder/src/ESP32Encoder.cpp: In function 'void pcnt_example_intr_handler(void*)':
libraries/ESP32Encoder/src/ESP32Encoder.cpp:40:25: error: 'PCNT' was not declared in this scope
  uint32_t intr_status = PCNT.int_st.val;
                         ^~~~
libraries/ESP32Encoder/src/ESP32Encoder.cpp:40:25: note: suggested alternative: 'OCT'
  uint32_t intr_status = PCNT.int_st.val;
                         ^~~~
                         OCT

A quick fix is to include soc/pcnt_struct.h in ESP32Encoder.h, but I cannot say if this leads to other complications.

2. After flashing with the "fix" the device starts, but main voltage/A shows 0 (power supply connected), so no power output.

Please make a new release with commit 81eb562 and 695b0be

**Comment by leeseungcheol** [comment]
Hello,

Sorry for the late response.

1. As you know, the compiling error is resolved by adding the "pcnt_struct.h" header in "ESP32Encoder" library.
[https://github.com/madhephaestus/ESP32Encoder/issues/48](url)
If you update the ESP32Encoder library to the latest version, the error should not occur.

But I don't understand the "no power output" issue. Is the issue still occurring?

**Comment by cedel1** [comment]
Recently I ran into the compilation problem myself. Maybe making the library versions (semi?)fixed in 'platformio.ini' would save time, lower the entry barrier and allow for more precise control over the result?

Something like:
```
...
lib_deps =
   madhephaestus/ESP32Encoder @ 0.10.1
```

Platformio library option settings: https://docs.platformio.org/en/latest/projectconf/sections/env/options/library/index.html

EDIT: Managed to get the project to compile OK, but it seems the power settings broke - so basically what the original reporter experienced, ie:

Depending on the fix and library versions, the project compiles, device starts (logo shows followed by power settings screen), but the top left part of display showing voltage of power supply shows "0.0V 0.0A" in red (or and the power channels cannot be started by pressing buttons (always stay on 0), blue led stays permanently on. The power output voltage and amperage, however, can be set and changed normally.

Updating to latest version of the TFT_eSPI library compiles with a warning, flashes to device but the SP3 lights up screen but stays gray (no logo, no power output settings).

**Comment by cedel1** [comment]
With the help from the forum, managed to piece together library and platform versions that seem to work. See https://github.com/hardkernel/smartpower3/pull/21 .

I see this as a temporary solution so people trying to build the codebase get functional result they can build on without trying to figure out what's wrong. Hopefully, update to newest library/platform versions will soon be possible.

**Comment by cedel1** [comment]
Think I found out what caused the problem, so no need to stick to old Espressif32 version. WIP https://github.com/hardkernel/smartpower3/pull/22

**Comment by dknubben** [comment]
> Think I found out what caused the problem, so no need to stick to old Espressif32 version. WIP #22

Thanks a lot, this seems to work!
